apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: azdo-agents
  labels:
    app: azdevops-agent
spec:
  replicas: 10 # previous number was 4, upping to 10 because HPA will NOT be deployed *yet*
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: kubepodcreation
        image: __ACR-NAME__.azurecr.us/ubuntu-agent:1.1.0
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 192Mi
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      imagePullSecrets:
      - name: acr-secret
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock