name: $(moduleName)

parameters:
- name: versioningOption
  displayName: Default publish version
  type: string
  default: patch
  values:
  - patch
  - minor
  - major
- name: uiCustomVersion
  displayName: -OR- Custom publish version
  type: string
  default: '-'
- name: removeDeployment
  displayName: Remove resources post-deployment
  type: boolean
  default: true

variables:
- template: /Modules/.global/global.variables.yml
- name : moduleName
  value: VirtualHub 

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Modules/.global/*
    - Modules/VirtualHub/*

stages:
  - stage: Go_Test
    jobs:
    - template: /Modules/.global/global.tests.yml